# This is a basic workflow to help you get started with Actions

name: CI

<<<<<<< HEAD
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  
=======
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

>>>>>>> 1b40a7cd2b7f50aa75a6850fdabff269b8c69fb0
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
<<<<<<< HEAD
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: setup node js environment
        uses: actions/setup-node@v2-beta
        with:
          version: 12

      # Runs a set of commands using the runners shell
      - name: installing yarn
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Creating Build
        run: yarn run build
        
      - name: installing surge
        run: npm install -g surge
        
      - name: deploying on surge
        run: surge ./build http://bootcamp2020byhamza.surge.sh --token ${{secrets.SURGE_TOKEN}}
        
      
          echo Add other actions to build,
          echo test, and deploy your project.
=======
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with: 
        version: 12
        
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v3.0.0
      with:
        # Yarn command
        cmd: install # npm install/ yarn install
    
    - name: Creating build
      run: yarn build
    
    - name: installing surge  
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build http://hamzabuild.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
    
    
>>>>>>> 1b40a7cd2b7f50aa75a6850fdabff269b8c69fb0
